### ISSUE TITLE
DxLib追加(必要分のみ)

### ISSUE THREAD

**Issue by gtgjpj** [daitovenom/Mutate2023#3]
DxLibを別途ダウンロードする必要が内容に当リポジトリに追加します。
DxLib本体の追加予定フォルダはMutate2023.vcxprojファイルと同じ階層に"DxLib"になります。
合わせて、Mutate2023.vcxprojがCドライブ直下にあるDxLibを参照しているため、
- [追加のインクルード ディレクトリ]項目
- [追加のライブラリ ディレクトリ]項目

を編集します。(x64/Win32, Release/Debugの4パターン)

準備でき次第、Pull Requestを作成する予定です。

**Comment by gtgjpj** [comment]
Issue #4 と関連する事項であるため、最終結果が出てからPull Requestを作成致します。
仮に32bit版(Win32)アプリケーションのみビルドすることになった場合、DxLibの"プロジェクトに追加すべきファイル_VC用”から、"x64"という名称を含むファイルを除去できるためです。
もちろん、あらかじめ準備は進めておきます。

**Comment by daitovenom** [comment]
わざわざどうもありがとうございます！
お手数をお掛け致します。

えと、みにまどん様の方で準備して頂いたものがこちらのエクスプローラにも反映されるということでしょうか。
内容を正しく判断できたかは不安なのですが、steamでは32bitしかリリースできないため、エクスプローラー内のx64のフォルダをみにまどん様を通して削除するということでしょうか？

**Comment by gtgjpj** [comment]
> 内容を正しく判断できたかは不安なのですが、steamでは32bitしかリリースできないため、エクスプローラー内のx64のフォルダをみにまどん様を通して削除するということでしょうか？

こちらにつきましては、Visual C++としまして基本的にはWin32フォルダやx64フォルダは成果物を出力するフォルダでありまして、ソースコードをそれらのフォルダに保存してしまいますと、ソースコードとアプリケーションがごちゃ混ぜ状態になってしまいます。
ですので、ソースコードはsourceフォルダにまとめて、Visual C++がビルドするときにWin32フォルダを作成してそこにアプリケーションが作成されるようにします。
エクスプローラー内のx64/Releaseフォルダにつきましては、syuzinnkouKENJYUU.hファイルが含まれております。
これは内容としてsourceフォルダにある同名ファイルと同じ内容のものになりますので、x64/Release以下はファイルなし(空フォルダ)になるよう修正します。
※プロジェクトファイル(Mutate2023.vcxproj, Mutate2023.vcxproj.filters)の修正も必要です。

**Comment by gtgjpj** [comment]
Pull Request #5 において、x64/Release/syuzinnkouKENJYUU.hのファイルを削除しまして、source/syuzinnkouKENJYUU.hを参照(使用)するように修正しています。
また、本件のタイトルにあります通り、Pull Request #5 においてCドライブ直下にDxLibのファイルを置く必要がなくなります。
Debug/Win32とRelease/Win32のビルドが通ることをご確認お願い致します。
ご予定は今のところないと思いますが、この部分がうまくいきますと、他の開発者を追加しやすくなります。
※開発環境の準備が簡単になります。

**Comment by daitovenom** [comment]
どうもありがとうございます！

＞＞DxLibはMutate2023.vcxprojファイルと同じ階層にDxLibフォルダを作成して必要な分(.hファイルと.libファイル)のみ追加致しました。
Debug/x86とRelease/x86のビルドが通ることをご確認お願い致します。

に関しましては、visual studio 2019に含まれるプログラムをみにまどん様が編集したプログラムに更新するということかと思いますが、どうやって更新すればいいのでしょうか。
お手数をお掛けして申し訳ありません。

**Comment by gtgjpj** [comment]
Cドライブの直下にある"C:\DxLib_VC"フォルダを一旦別の場所に移動して頂いた上で、ビルドができるかどうか確認して頂ければと思います。
これ状況においてビルドができて、可能であれば実行もできればOKです。
お伝えしておりました通り、私も含め他の開発者が手を加えるときにも、非常にビルド環境構築が楽になります。
なお、まだ画像・BGMなどを追加していない状態ですので、ご注意下さい。

**Comment by daitovenom** [comment]
無事できました！
ありがとうございます！

**Comment by gtgjpj** [comment]
お忙しい中、ご確認頂きまして有難うございます。
当件、Closeとさせて頂きます。
改めて、ご確認感謝致します。ありがとうございます。
次は、メディアファイル(画像・BGM・効果音)について対応を行っておりますので、Issue #7 などをご覧くださいませ。
