### ISSUE TITLE
[要協議事項] 64bit版ビルド(x64)の取りやめ

### ISSUE THREAD

**Issue by gtgjpj** [daitovenom/Mutate2023#4]
[要協議事項]
2023/05/27時点のプロジェクトファイルによると、Windows向けの32bit版(Win32)と64bit版(x64)のアプリケーションが作成できるようになっています。
Steamなどを参考にしてみますと、Steam自体Windows向けとして32bit版しかリリースされていないようになっています。これは64bit版のWindowsでは32bit版(Win32)のアプリケーションを問題なく実行することができるようOS自身が互換性を持たせているためです。
当プロジェクトから64bit版(x64)のアプリケーションビルドを除外することを検討していますがいかがでしょうか？
大規模な3Dゲームであれば、64bit版のアプリケーションをリリースする必要があるかもしれません。
必要なときになって、再度検討できればとおもいます。

コメントなどがありましたら、十分に検討して頂いた上でお願い致します。

**Comment by daitovenom** [comment]
ご連絡ありがとうございます。

＞＞当プロジェクトから64bit版(x64)のアプリケーションビルドを除外することを検討していますがいかがでしょうか？

Steam自体Windows向けとして32bit版しかリリースされていないとは知りませんでした！
貴重な情報ありがとうございます！！

ちなみに、以前switchでリリース場合はunityで開発するしかないと聞いたことがあるのですが、本当でしょうか。

**Comment by gtgjpj** [comment]
コメントありがとうございます。

> Steam自体Windows向けとして32bit版しかリリースされていないとは知りませんでした！

ひとまず、Steamのスタンスに倣って64bit版(x64)のアプリケーションビルドを除外する方向で進めます。

> ちなみに、以前switchでリリース場合はunityで開発するしかないと聞いたことがあるのですが、本当でしょうか。

まず、DXライブラリとしましては以下の見解となっております。
https://dxlib.xsrv.jp/dxswitch.html

以下のWebサイト(Play.Doujin!)にサークルとして登録することで、家庭用ゲーム機にゲームをリリースすることができるようです。
しかし、条件が厳しいことをご理解下さい。
https://playdoujin.mediascape.co.jp/new-circle-info/

**Comment by gtgjpj** [comment]
Pull Request #5 によって当IssueはCloseする予定です。
※Pull Request #5 で問題がなければという前提になりますが・・・。

**Comment by daitovenom** [comment]
わざわざ調べて下りありがとうございます。
仮に開発できたとしても発売する上での困難な部分があることがわかりました。

**Comment by gtgjpj** [comment]
Pull Request #5 がマージされましたので、当件Close扱いと致します。
コメントありがとうございました。

**Comment by daitovenom** [comment]
どうもありがとうございます！

**Comment by gtgjpj** [comment]
ご返信下さり有難うございます。
"Closed"というステータスになっておりますが、コメントを追記して"Reopen with comment"というボタンを押して頂くことで、再度、当件の問題提起または議論を行うことができますのでよろしくお願い致します。
