### ISSUE TITLE
[書籍]「ゆっくり動く」と人生が変わる 副交感神経アップで、心と体の「不調」が消える！

### ISSUE THREAD

**Issue by gtgjpj** [daitovenom/Mutate2023#9]
Pull Request #5 のコメントにてコメントがありましたので、Issueを作成しました。

自律神経を整えることは大事なことです。
一般的に、パソコンやスマートフォンの画面を見ると、交感神経優位になります。
仕事をハードに行う人はさらにコーヒーなどを飲んで、交感神経をさらに優位にさせて仕事に集中できるようにします。
しかし、人間は交感神経優位状態を長い間維持すると、今度は体や神経系(精神)に負担がかかってきますし、寝つきも悪くなります。

こちらは犯罪捜査における文献ですが、自律神経の反応とリンクしていることが分かります。
https://www.jstage.jst.go.jp/article/sjpr/59/2/59_162/_pdf

おそらく、人が犯罪を犯す前後においても、自律神経は大きくバランスを崩し、交感神経優位になるはずです。
それは犯罪を犯したことを自認している場合に限りますが。
常に交感神経優位で常に寝不足で現実と夢の境界が分からなくなる人もいます。そのような人の場合でも、犯罪を犯したときには交感神経がさらに優位となります。

無意識に犯罪者となった方もいます。それは犯罪者予備軍の方でもなく、一般人です。
一般人でも犯罪に巻き込まれたら、犯罪者となりうることがあります。
昨今では自殺ほう助で逮捕されてしまった医師の方がいますし(逮捕されることは覚悟されていたと思いますが)、イノシシと間違えて人に向かって猟銃で撃ってしまった猟師の方もいます。

日本は法治国家ですが、海外はどうでしょうか？
それらを考慮すると犯罪であるか否かというものはあやふやな気がしてなりません。

**Comment by daitovenom** [comment]
ありがとうございます。


>>無意識に犯罪者となった方もいます。それは犯罪者予備軍の方でもなく、一般人です。
一般人でも犯罪に巻き込まれたら、犯罪者となりうることがあります。
昨今では自殺ほう助で逮捕されてしまった医師の方がいますし(逮捕されることは覚悟されていたと思いますが)、イノシシと間違えて人に向かって猟銃で撃ってしまった猟師の方もいます。


これに関しましては難しい話ではありますが、明確な悪意があったわけではなく、犯罪予備軍とは言えないため...まずは、犯罪予備軍の方をどう止めるかを考えたいと思います。


>>自律神経を整えることは大事なことです。
一般的に、パソコンやスマートフォンの画面を見ると、交感神経優位になります。
仕事をハードに行う人はさらにコーヒーなどを飲んで、交感神経をさらに優位にさせて仕事に集中できるようにします。
しかし、人間は交感神経優位状態を長い間維持すると、今度は体や神経系(精神)に負担がかかってきますし、寝つきも悪くなります。

現代の大きな問題と言えますね。
こういう問題は薬物治療などができれば良いですが、治療が必要な人間というのは犯行を起こした後気がつく事が多いです。
京アニ事件、最近の長野の事件、渋谷ジョーカー事件などは犯行を犯してから加害者が異常者だとわかりました。

そんな彼らの周りにいる誰かが1人でも相談相手になってあげられたり警察に通報していれば大事にならずに済んだかも知れません。

もちろん、今開発しているゲームを健常者がプレイして、こういう人間が身近にいたら相談に乗ってあげたり警察に通報するなり相談した方がいいなぁと考えてくれたら犯罪は減るんじゃないかなと、考えていますが、
そんな簡単に開発したゲームが浸透するはずもなく、そんな都合よく話が進むわけはないと考えています。

**Comment by gtgjpj** [comment]
ご返信ありがとうございます。

おっしゃる通り難しい問題でございます。
少し、興味がありますので「マインドマップ」というものを描いてみたいと思います。(もちろん、当アプリケーションの作業を優先致します)
今も昔も歴史的にみても犯罪というのは起きています。人間はそういうものだという前提の上で心理上(理性による抑制)であったり環境面であったり人間関係であったり要因が複雑すぎるため、マインドマップを描いてみたいと思います。

**Comment by gtgjpj** [comment]
当Issueにつきましては、一旦Closeさせて頂きまして、必要に応じて再Openとさせて頂きます。(議論する必要が発生した場合など)
ご了承くださいませ。
